import { writeFileSync } from "node:fs";
import sharp from "sharp";

/**
 * The supplied hero banner is a 1.8MB PNG. A photograph has no business being
 * a PNG, and the optimiser should not re encode two megabytes on a cold cache.
 *
 * This writes a right sized JPEG source that next/image then negotiates to
 * AVIF or WebP per browser, plus a tiny inline blur placeholder so the hero
 * has something to show while the full image arrives.
 *
 * Run again if the hero artwork changes:  npx tsx scripts/optimise-hero.ts
 */

const SOURCE = "public/use-this-as-hero.png";
const OUTPUT = "public/hero-banner.jpg";
const BLUR_MODULE = "lib/hero-blur.ts";

async function main() {
  const input = sharp(SOURCE);
  const meta = await input.metadata();

  const info = await input
    .clone()
    .resize({ width: 2000, withoutEnlargement: true })
    .jpeg({ quality: 74, mozjpeg: true })
    .toFile(OUTPUT);

  // A 20px wide version, inlined as a data URI. Small enough to sit in the
  // HTML without measurably affecting the payload.
  const blur = await input.clone().resize({ width: 20 }).jpeg({ quality: 45 }).toBuffer();
  const blurDataURL = `data:image/jpeg;base64,${blur.toString("base64")}`;

  writeFileSync(
    BLUR_MODULE,
    [
      "/**",
      " * Generated by scripts/optimise-hero.ts. Do not edit by hand.",
      " * A 20px wide encoding of the hero, inlined as the blur placeholder.",
      " */",
      `export const HERO_BLUR = "${blurDataURL}";`,
      "",
    ].join("\n"),
  );

  const sourceKb = Math.round((meta.size ?? 0) / 1024);
  const outputKb = Math.round(info.size / 1024);

  console.log(`Hero: ${meta.width}x${meta.height} PNG at ${sourceKb}KB`);
  console.log(`  ->  ${info.width}x${info.height} JPEG at ${outputKb}KB (${OUTPUT})`);
  console.log(`  blur placeholder: ${blur.length} bytes -> ${BLUR_MODULE}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
